### ISSUE TITLE
system spec がうまく実行されていない。

### ISSUE THREAD

**Issue by kazu-2020** [kazu-2020/arrangy#21]
## 問題
system spec実行時に失敗した際のscreenshotに何も表示されません。

[![Image from Gyazo](https://i.gyazo.com/81d4d05d1c31f757472db3c2355087c6.png)](https://gyazo.com/81d4d05d1c31f757472db3c2355087c6)

## 各種バージョン
- Rails 6.0.0.5
- Ruby 2.7.2
- @vue/cli 4.5.11
- rspec-rails 4.0.2

 ## 実行したテストコード
ユーザー登録画面に移動し、「登録」ボタンをクリックするテストです。
```ruby
require 'rails_helper'

RSpec.describe "ユーザー登録", type: :system, js: true do
  context 'ユーザー情報に不備がある場合' do
    before do
      visit '/register'
      click_on 'メールアドレスで登録'
    end
    it '新規登録に失敗する' do
      expect(page).to have_content 'ニックネームは必須項目です'
    end
  end
end
```

こちらがテストを実行したい画面です。

[![Image from Gyazo](https://i.gyazo.com/c5128283b87805d51cfda18723bbf03a.png)](https://gyazo.com/c5128283b87805d51cfda18723bbf03a)

## 該当するコード

spec/support/capybara.rb
```ruby
RSpec.configure do |config|
  config.before(:each, type: :system) do
    driven_by :rack_test
  end

  config.before(:each, type: :system, js: true) do
    driven_by :selenium_chrome_headless
  end
end
```

spec/rails_helper.rb
```ruby
# spec/support下を読み込む為に追加。
Dir[Rails.root.join('spec/support/**/*.rb')].sort.each { |f| require f }
```

## 試したこと
こちらの[issue](https://github.com/rspec/rspec-rails/issues/2153)に似たような問題が上がっていましたが、
自分のrspec-railsのバージョンは既に4系でした。

**Comment by yuji91** [comment]
「07_update_register_function」が対象のブランチ。
他のリポジトリでスクリーンショット機能が動作するかは検証中。

**Comment by kazu-2020** [comment]
他のリポジトリではsystem spec を実行していなかった為、検証しておりません。

その為、課題でRspecを実行した際のログの差異を見てみました。

- 課題vue編のRspec実行時のログ
「タスク管理」下で、capybaraがpumaを起動しているのがログで確認できる。
[![Image from Gyazo](https://i.gyazo.com/9c5b4e53ae5e6df71c3349c5caa82115.png)](https://gyazo.com/9c5b4e53ae5e6df71c3349c5caa82115)

- 自分のRspec実行時のログ
capybaraがpumaを起動しているのがログで確認できない。

[![Image from Gyazo](https://i.gyazo.com/c83013bdaa1a62bb4f9d70b96076fa6c.png)](https://gyazo.com/c83013bdaa1a62bb4f9d70b96076fa6c)

**Comment by yubachiri** [comment]
試しにapplication.html.erbにこんな風に書いてみると、その内容はスクリーンショットに表示されることが確認できました。
なのでテスト時にvueが描画できていないのかなと思います。引き続き調査してみますね。

```
<!DOCTYPE html>
<html>

略

  <body>
    <%= yield %>
    <p>hoge</p>
  </body>
</html>
```

![failures_r_spec_example_groups_nested_nested_新規登録に失敗する_387](https://user-images.githubusercontent.com/31993933/109964263-cc095d00-7d30-11eb-9f24-72d2dc667f57.png)

**Comment by kazu-2020** [comment]
@yubachiri 
自分の環境でも確認できました!!
そうすると、テスト環境でwebpackerのコンパイルが実行されていないのが問題ですかね?

**Comment by yubachiri** [comment]
public/packs-test下にファイルが生成されていて、save_and_open_pageで生成されたhtmlからもそこを見にいっている風なコードが書いてあったので、コンパイルはされているのかなぁ…？と思います。
まだ「これ！」といった原因と解決策がわかってないので、引き続きもうちょっと見てみます！

**Comment by kazu-2020** [comment]
よろしくお願いします!

**Comment by kazu-2020** [comment]
原因が分かりました!!

axiosの設定でリクエストヘッダーに`csrf-token`を追加してリクエストを送るようにしていたのですが、それが駄目だったようです。

app/frontend/plugins/axios
```
import axios from 'axios';

let csrf_token = document.getElementsByName('csrf-token')[0].content; #<= ここでエラーが発生している!!
const axiosInstance = axios.create({
  baseURL: '/api',
  headers: { 'X-CSRF-TOKEN': csrf_token },
});

export default axiosInstance;
```

「driven_by :selenium_chrome 」でデバックした際の画像

[![Image from Gyazo](https://i.gyazo.com/74e9d6be4c0ddb351ff2fdc29cf3e4d8.png)](https://gyazo.com/74e9d6be4c0ddb351ff2fdc29cf3e4d8)

その為、csfr-tokenの箇所をコメントアウトしたところvue.jsが反映されました。

[![Image from Gyazo](https://i.gyazo.com/126c62dcbe93dd4b1eb58f3f7824ec51.png)](https://gyazo.com/126c62dcbe93dd4b1eb58f3f7824ec51)

**Comment by kazu-2020** [comment]
しかし、「csrf_token = document.getElementsByName('csrf-token')[0].content」のコードがないとPostリクエストの際に、Rails側からエラーを吐かれてしまいます。
どうしたらいいかアドバイスもらえませんか?

**Comment by kazu-2020** [comment]
上記の問題への対応は[こちら](https://tech.medpeer.co.jp/entry/2018/02/26/080000)の記事を参考に、jsのライブラリとして提供されている「rails-ujs」を導入することで回避できました。
