### ISSUE TITLE
oauth認証でcorsの問題を解決したい

### ISSUE THREAD

**Issue by kazu-2020** [kazu-2020/arrangy#38]
## やりたいこと
Sorceryの[external](https://github.com/Sorcery/sorcery/wiki/External)を使用して、googleのOauth認証を行いたいです。

対応しているブランチ  => 18_twitter_authentication 

## 発生している問題
[![Image from Gyazo](https://i.gyazo.com/4a31a03ffcc5d74538bc0a201494116b.png)](https://gyazo.com/4a31a03ffcc5d74538bc0a201494116b)

RailsからGoogle認証にリクエストを送った際、「Access-Control-Allow-Origin」の設定に不備がある為に起きていると思われます。

## 聞きたいこと
こちらのエラーはRails側で「Access-Control-Allow-Origin」の設定を追加しないといけないのでしょうか ?
セキリュティに直結しそうで怖いので、アドバイスを頂きたいです。

## 対象のコード
- Google側の設定
[![Image from Gyazo](https://i.gyazo.com/ecfcc0370b6f21f048ffe144f14182e4.png)](https://gyazo.com/ecfcc0370b6f21f048ffe144f14182e4)
config/initializers/sorcery.rb

```ruby
  config.google.key = Rails.application.credentials.google[:access_key_id]
  config.google.secret = Rails.application.credentials.google[:secret_access_key]
  config.google.callback_url = "http://127.0.0.1:3000/oauth/callback?provider=google"
  config.google.user_info_mapping = {:email => "email", :nickname => "name"
```

routes.rb
```ruby
Rails.application.routes.draw do
  namespace :api, format: 'json' do
    ・・・
    post "oauth/callback", to: "oauths#callback"
    get "oauth/callback",  to: "oauths#callback"
    get "oauth/:provider", to: "oauths#oauth", as: :auth_at_provider
  end
  get '*path', to: 'static_pages#top'
  root 'static_pages#top'
end
```

controllers/api/oauths_controller.rb
```ruby
class Api::OauthsController < ApplicationController
  skip_before_action :require_login

  def oauth
    # binding.pry
    # login_at(params[:provider])
    login_at(:google)  <= ここが実行された際にエラーが発生しています。
  end

  def callback
    provider = params[:provider]
    if @user = login_from(provider)
      redirect_to root_path
    else
      begin
        @user = create_from(provider)
        reset_session
        auto_login(@user)
        redirect_to root_path
      rescue
        redirect_to root_path
      end
    end
  end
end
```

**Comment by MrFuku** [comment]
@kazu-2020 
「承認済みの JavaScript 生成元」に`http://localhost:3000`を入れるとどうなるか試してもらっていいですか？

**Comment by MrFuku** [comment]
できればレスポンスヘッダーがどう変わるかビフォーアフターを見てみたいです！

**Comment by kazu-2020** [comment]
夜遅くに解答ありがとうございます!!
> 承認済みの JavaScript 生成元」に`http://localhost:3000`を入れるとどうなるか試してもらっていいですか？

こちらはエラー内容に変化は見られませんでした...

レスポンスヘッダーの画像は今から送ります!!

**Comment by kazu-2020** [comment]
すみません、伝え忘れていたのですがどうも同じリクエストが送られているみたいです。

- １回目
[![Image from Gyazo](https://i.gyazo.com/f787ce28035c926df7d6ffbf57f916ef.png)](https://gyazo.com/f787ce28035c926df7d6ffbf57f916ef)

- 2回目
[![Image from Gyazo](https://i.gyazo.com/cee76c2ce65131d19201269be18fedaf.png)](https://gyazo.com/cee76c2ce65131d19201269be18fedaf)

[![Image from Gyazo](https://i.gyazo.com/cc29695724ddc26d9f61e8d7a1975a4a.png)](https://gyazo.com/cc29695724ddc26d9f61e8d7a1975a4a)

**Comment by MrFuku** [comment]
難しいですね...
明日再挑戦しますm(__)m

**Comment by kazu-2020** [comment]
すみません、よろしくお願いします !!

**Comment by pkshimizu** [comment]
Access-Control-Allow-Originは、CORS (Cross-Origin Resource Sharing)というセキュリティに関する設定で、詳しくは以下の記事を参考にしてください
https://qiita.com/tomoyukilabs/items/81698edd5812ff6acb34

今回は、localhost:3000というホストから、googleに対してリクエストを送っているため、CORSが発生しています
これを許可するために、「承認済みの JavaScript 生成元」の設定があり、ここにlocalhost:3000を追加することでCORSが解消します

上記で、「承認済みの JavaScript 生成元」を設定されているようですが、googleからのレスポンス結果が変わっていないようなので、正しく設定できていないように思えます
もう一度、Googleの設定キャプチャ画像を見せていただけるでしょうか？

**Comment by kazu-2020** [comment]
@pkshimizu 
「保存」ボタンを押した後に確認したのですが変化ありません。
後、`http://127.0.0.1:3000`も試したのですが変化ありませんでした。

[![Image from Gyazo](https://i.gyazo.com/cc748055ba42d04b8cdfcaf8ceb5556e.png)](https://gyazo.com/cc748055ba42d04b8cdfcaf8ceb5556e)

**Comment by kazu-2020** [comment]
vueからaxiosを使用して`GET http://localhost3000/oauth/google`でRailsにアクセスしているのですが、
axiosの設定の問題は考えられますか?

**Comment by pkshimizu** [comment]
CORSは、サーバー側でどこからのアクセスを許可するかの設定なので、フロント側の設定は不要です
ただ、vueでproxyを使っている場合は、そのproxyの設定に合わせてCORSを設定する必要がありますが、proxyは利用しているでしょうか？

**Comment by kazu-2020** [comment]
使用していないです!!
一応、webpackerを使用してvueを導入している形です。

**Comment by pkshimizu** [comment]
あ、oauth2はaxios（ajax）はサポートしていないですね
以下の記事などを参考にして、vue.jsでのoauth2の実装をしてみてください
https://lonesec.com/2020/09/05/vuejs-google-auth-development/

**Comment by MrFuku** [comment]
あまり関係ないかもしれませんが、`<v-btn class="mb-12" xLarge @click="handleRegisterGoogle">Googleアカウントで登録</v-btn>`のところを非Ajaxにするとどうなりますか？

ただのaタグにした場合どうなるかみてみたいです

補足
公式ではajaxを使わない手順しかなかったので、とりあえず試してみたいという感じです
https://github.com/Sorcery/sorcery/wiki/External

**Comment by kazu-2020** [comment]
@MrFuku 
> <v-btn class="mb-12" xLarge @click="handleRegisterGoogle">Googleアカウントで登録</v-btn>のところを非Ajaxにするとどうなりますか？

```vue
<v-btn class="mb-12" xLarge href="/api/oauth/google">Googleアカウントで登録</v-btn>
```
動きました...
ですが、理由が分かりません。これはshimizuさんが言われている`oauth2はaxios（ajax）はサポートしていない`ということに関係があるのですか？

**Comment by MrFuku** [comment]
ぶっちゃけなんでかは僕も良くわかんないですが、公式の手順との差分考えたらそこしかないと思いまして（テキトー笑）

**Comment by pkshimizu** [comment]
axios（ajax)ではなく、ページ線で実装して動くようになったということですね
この機に、OAuth2の仕組みについて、正しく理解しておくと良いと思います（その理解によって何故ajaxがサポートされていないのかも理解できると思います）
https://murashun.jp/article/programming/oauth2.html

**Comment by kazu-2020** [comment]
@MrFuku  @pkshimizu 
対応ありがとうございました!!
自分の中で内容を整理して進めたいと思います。
